### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by chrise86** [dblandin/motion-form#3]
This may seem stupid (I am _very_ tired) but how do I use this? I'm trying in a ProMotion screen...

Adding the `form = MotionForm.form_for(view) do |form|` block to the `on_load` gives the following when opening the screen:

```
uninitialized constant NewsletterScreen::MotionForm (NameError)
```

**Comment by sorentwo** [comment]
Are you sure you have required `motion_form` somewhere? Looks like a common missing module error.

**Comment by chrise86** [comment]
Ah I believe I was using `require 'motion-form'`... thanks!
